version: '3.7'

services:
  oracle:
    build:
      context: ""
      dockerfile: docker/oracle.dockerfile
    container_name: oracle
    environment:
      ORACLE_SID: orcl
      #ORACLE_PDB: oracle
      ORACLE_PWD: oracle
      ORACLE_CHARACTERSET: AL32UTF8
      ORACLE_EDITION: enterprise
      ENABLE_ARCHIVELOG: 'false'
      INIT_SGA_SIZE: 3000
      INIT_PGA_SIZE: 1000
    volumes:
      - oradata:/opt/oracle/oradata # persistent oracle database data      
    ports:
      - 1521:1521
      - 5500:5500
    networks:
      - backbone
    entrypoint: ["/bin/sh"]
    command: ["-c", "/home/oracle/custom_scripts/run_sql_scripts.sh && exec /bin/sh -c /opt/oracle/runOracle.sh"]

  airflow-database:
    build:
      context: ""
      dockerfile: docker/postgres.dockerfile
    container_name: airflow_database
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    #ports:
    #  - "5432:5432"
    env_file:
      - docker/postgres/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backbone

  airflow:
    build:
      context: .
      dockerfile: docker/airflow.dockerfile
    container_name: airflow
    restart: always
    depends_on:
      - airflow-database
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "9999:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - airflow-logs:/opt/airflow/log
      - ${PWD}/docker/airflow/airflow.cfg:/opt/airflow/airflow.cfg
    networks:
      - backbone

volumes:
  oradata: {}
  postgres-data: {}
  airflow-logs: {}

networks:
  backbone:
    driver: bridge
